Repository cloud-native-toolkit/terraform-gitops-ocp-cert-manager, pull requests merged in 2022-02, with the labels that each got.

#2 operator deploy
  .github/scripts/validate-deploy.sh
  .github/workflows/verify.yaml
  README.md
  chart/cert-job.yaml
  main.tf
  module.yaml
  scripts/create-yaml.sh
  test/stages/stage1-cluster.tf
  test/stages/stage1-gitops-bootstrap.tf
  test/stages/stage1-namespace.tf
  test/stages/stage2-certmgr.tf
  test/stages/variables.tf
  variables.tf
Labels: enhancement, major

#4 Removes cluster dependency from metadata and updates workflows
  .github/scripts/validate-deploy.sh
  .github/workflows/publish-assets.yaml
  .github/workflows/verify.yaml
  chart/cert-job.yaml
  module.yaml
  test/stages/stage1-gitops-bootstrap.tf
  test/stages/variables.tf
  variables.tf
Labels: patch, chore

#5 Updates deployment process to use kustomize and 1.2 script
  .github/scripts/validate-deploy.sh
  .github/workflows/verify.yaml
  chart/base/cert-manager.yaml
  chart/cert-job.yaml
  chart/kustomization.yaml
  chart/patches/webhook-namespace-selector.yaml
  main.tf
  outputs.tf
  scripts/create-yaml.sh
  test/stages/stage1-olm.tf
  test/stages/stage1-resource-group.tf
  test/stages/stage2-certmgr.tf
  test/stages/stage3-outputs.tf
  test/stages/variables.tf
  variables.tf
Labels: enhancement, minor

#6 Converts to use gitops provider
  .github/scripts/validate-deploy.sh
  main.tf
  module.yaml
  outputs.tf
  test/stages/provider.tf
  test/stages/stage0.tf
  test/stages/stage2-certmgr.tf
  variables.tf
  version.tf
Labels: enhancement, minor

#7 Use local file for cert-manager
  .github/scripts/validate-deploy.sh
  main.tf
Labels: bug, patch
